// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionTemporary.Models.Entities;

#nullable disable

namespace PensionTemporary.Migrations
{
    [DbContext(typeof(PensionContext))]
    [Migration("20241205043115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankFile", b =>
                {
                    b.Property<string>("Column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BankFiles");
                });

            modelBuilder.Entity("DepartmentFileModel", b =>
                {
                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionOnDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppliedDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppliedTehsil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfscCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JK_ISSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JanSugamDownloadCycle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthActionOnDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PensionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentTehsil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Present_GP_Muncipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousPension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousPensionAccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousPensionBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousPensionBankBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousPensionBankIFSCcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanctionedByTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TswoPreviousPensionScheme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TswoPreviousPensionYesNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfDisabilityAsPerUDID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearActionOnDate")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DepartmentFileModels");
                });

            modelBuilder.Entity("FileUploaded", b =>
                {
                    b.Property<bool>("BulkUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("FileUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedColumn")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.CasesStopped", b =>
                {
                    b.Property<string>("DistrictLgdcode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("districtLGDcode");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("districtName");

                    b.Property<string>("InfRecvdInnicOn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("infRecvdINnicOn");

                    b.Property<string>("LetterDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("letterDate");

                    b.Property<string>("LetterFrom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("letterFrom");

                    b.Property<string>("LetterNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("letterNo");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Parentage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("parentage");

                    b.Property<string>("Reason1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason1");

                    b.Property<string>("Reason2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason2");

                    b.Property<string>("Reason3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason3");

                    b.Property<string>("ReasonForStoppingPension")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reasonForStoppingPension");

                    b.Property<string>("RefNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("refNo");

                    b.Property<int?>("Uid")
                        .HasColumnType("int")
                        .HasColumnName("uid");

                    b.ToTable("casesStopped", (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.JkSwdeliveredMay30", b =>
                {
                    b.Property<string>("AccountNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("accountNo")
                        .HasComment("Defines the account number of the applicant");

                    b.Property<string>("AccountNoCorrectionByDirectorate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("accountNoCorrectionByDirectorate");

                    b.Property<DateTime?>("AccountNoCorrectionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("accountNoCorrectionDate");

                    b.Property<string>("AccountNoCorrectionDirLetter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("accountNoCorrectionDirLetter");

                    b.Property<string>("ActionOnDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("actionOnDate");

                    b.Property<string>("ActionOnDateVerified1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("actionOnDate_verified1");

                    b.Property<string>("AppliedDistrict")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("appliedDistrict");

                    b.Property<string>("AppliedTehsil")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("appliedTehsil");

                    b.Property<string>("AprilChk")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("aprilChk");

                    b.Property<string>("AprilChk2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("aprilChk2");

                    b.Property<string>("AprilChk3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("aprilChk3");

                    b.Property<string>("ArearBankFileBankPaymentOk")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("arear_bank_file_bankPayment_ok");

                    b.Property<string>("ArearBankFileBankPaymentOkDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("arear_bank_file_bankPayment_ok_date");

                    b.Property<int?>("ArrearApril23MinusMarch23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_April23_Minus_March23");

                    b.Property<int?>("ArrearAug23MinusJuly23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_Aug23_Minus_July23");

                    b.Property<string>("ArrearBankFileGenerated")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("arrear_bank_file_generated");

                    b.Property<string>("ArrearBankFileGeneratedDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("arrear_bank_file_generated_date");

                    b.Property<int?>("ArrearDec23MinusNov23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_Dec23_Minus_Nov23");

                    b.Property<int?>("ArrearFeb24MinusJan24")
                        .HasColumnType("int")
                        .HasColumnName("arrear_Feb24_Minus_Jan24");

                    b.Property<int?>("ArrearJan24MinusDec23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_Jan24_Minus_Dec23");

                    b.Property<int?>("ArrearJuly23MinusJune23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_July23_Minus_June23");

                    b.Property<int?>("ArrearJune23MinusMay23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_June23_Minus_May23");

                    b.Property<int?>("ArrearMar24MinusFeb24")
                        .HasColumnType("int")
                        .HasColumnName("arrear_Mar24_Minus_Feb24");

                    b.Property<int?>("ArrearMarch23MinusFeb23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_March23_Minus_Feb23");

                    b.Property<int?>("ArrearMay23MinusApril23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_May23_Minus_April23");

                    b.Property<int?>("ArrearNov23MinusOct23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_Nov23_Minus_Oct23");

                    b.Property<int?>("ArrearOct23MinusSep23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_Oct23_Minus_Sep23");

                    b.Property<int?>("ArrearSep23MinusAug23")
                        .HasColumnType("int")
                        .HasColumnName("arrear_Sep23_Minus_Aug23");

                    b.Property<int?>("ArrearTotalMonths")
                        .HasColumnType("int")
                        .HasColumnName("arrear_total_months");

                    b.Property<int?>("ArrearTotalMonthsAmt")
                        .HasColumnType("int")
                        .HasColumnName("arrear_total_months_amt");

                    b.Property<string>("BankFileGeneratedBeforeDirCorrection")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankFileGeneratedBeforeDirCorrection");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankName");

                    b.Property<string>("BankNameCorrectionByDirectorate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankNameCorrectionByDirectorate");

                    b.Property<string>("BankNameCorrectionDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankNameCorrectionDate");

                    b.Property<string>("BankNameCorrectionDirLetter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankNameCorrectionDirLetter");

                    b.Property<string>("BranchName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("branchName");

                    b.Property<string>("BranchNameCorrectionByDirectorate")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("branchNameCorrectionByDirectorate")
                        .IsFixedLength();

                    b.Property<string>("ChkAccountNoUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chkAccountNoUpdated");

                    b.Property<string>("ChkIfscCodeUpdated")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chkIfscCodeUpdated");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("currentStatus");

                    b.Property<string>("DeptVerified")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("deptVerified")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeptVerifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deptVerifiedDate");

                    b.Property<int?>("DistrictLgdcode")
                        .HasColumnType("int")
                        .HasColumnName("districtLGDCode");

                    b.Property<string>("DistrictNameForBank")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("districtNameForBank");

                    b.Property<string>("DistrictUidForBank")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("districtUidForBank");

                    b.Property<int?>("DivisionCode")
                        .HasColumnType("int")
                        .HasColumnName("divisionCode");

                    b.Property<string>("DivisionName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("divisionName");

                    b.Property<string>("Dob")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dob");

                    b.Property<string>("DummyCol")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dummyCol");

                    b.Property<string>("DuplicateBankAccountNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duplicateBankAccountNo");

                    b.Property<string>("EligibleForPension")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("eligibleForPension")
                        .HasComment("Defines whether applicant is eligible to receive pension or not");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gender");

                    b.Property<string>("GoiNsap")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GOI_NSAP");

                    b.Property<string>("IfscCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ifscCode")
                        .HasComment("Defines the Ifsc Code of the applicant");

                    b.Property<string>("IfscCorrectionByDirectorate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ifscCorrectionByDirectorate");

                    b.Property<DateTime?>("IfscCorrectionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ifscCorrectionDate");

                    b.Property<string>("IfscCorrectionDirLetter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ifscCorrectionDirLetter");

                    b.Property<string>("JanSugamDownloadCycle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("janSugamDownloadCycle");

                    b.Property<string>("JkIsss")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("JK_ISSS");

                    b.Property<string>("JunePaymentMonth2ndBnkFile2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("junePaymentMonth2ndBnkFile2023");

                    b.Property<string>("LeftOutCasesDueToSchemeClarification")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("leftOutCasesDueToSchemeClarification");

                    b.Property<int?>("LgdStateCode")
                        .HasColumnType("int")
                        .HasColumnName("lgdStateCode");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mobileNo");

                    b.Property<string>("MonthActionOnDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("monthActionOnDate");

                    b.Property<string>("MonthActionOnDateVerified1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("monthActionOnDate_verified1");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name")
                        .HasComment("Defines the name of the applicant");

                    b.Property<string>("NameCorrectionByDirectorate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nameCorrectionByDirectorate");

                    b.Property<DateTime?>("NameCorrectionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("nameCorrectionDate");

                    b.Property<string>("NameCorrectionDirLetter")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nameCorrectionDirLetter");

                    b.Property<string>("NsapChk")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nsapChk");

                    b.Property<string>("OctPaymentMonth2ndBnkFile2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("octPaymentMonth2ndBnkFile2023");

                    b.Property<string>("OctPaymentMonth2ndBnkFile20232")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("octPaymentMonth2ndBnkFile2023_2");

                    b.Property<string>("OldCdacbenificary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("oldCDACbenificary");

                    b.Property<string>("Parentage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("parentage");

                    b.Property<string>("PaymentOfMonthApril2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthApril2023");

                    b.Property<string>("PaymentOfMonthApril2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthApril2023BankRes");

                    b.Property<string>("PaymentOfMonthAug2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthAug2023");

                    b.Property<string>("PaymentOfMonthAug2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthAug2023BankRes");

                    b.Property<string>("PaymentOfMonthDec2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthDec2023");

                    b.Property<string>("PaymentOfMonthDec2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthDec2023BankRes");

                    b.Property<string>("PaymentOfMonthFeb2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthFeb2023");

                    b.Property<string>("PaymentOfMonthFeb2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthFeb2023BankRes");

                    b.Property<string>("PaymentOfMonthFeb2024")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthFeb2024");

                    b.Property<string>("PaymentOfMonthFeb2024BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthFeb2024BankRes");

                    b.Property<string>("PaymentOfMonthJan2024")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthJan2024");

                    b.Property<string>("PaymentOfMonthJan2024BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthJan2024BankRes");

                    b.Property<string>("PaymentOfMonthJuly2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthJuly2023");

                    b.Property<string>("PaymentOfMonthJuly2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthJuly2023BankRes");

                    b.Property<string>("PaymentOfMonthJune2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthJune2023");

                    b.Property<string>("PaymentOfMonthJune2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthJune2023BankRes");

                    b.Property<string>("PaymentOfMonthMarch2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthMarch2023");

                    b.Property<string>("PaymentOfMonthMarch2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthMarch2023BankRes");

                    b.Property<string>("PaymentOfMonthMay2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthMay2023");

                    b.Property<string>("PaymentOfMonthMay2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthMay2023BankRes");

                    b.Property<string>("PaymentOfMonthNov2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthNov2023");

                    b.Property<string>("PaymentOfMonthNov2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthNov2023BankRes");

                    b.Property<string>("PaymentOfMonthOct2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthOct2023");

                    b.Property<string>("PaymentOfMonthOct2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthOct2023BankRes");

                    b.Property<string>("PaymentOfMonthSep2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthSep2023");

                    b.Property<string>("PaymentOfMonthSep2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfMonthSep2023BankRes");

                    b.Property<string>("PaymentOfYearApril2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearApril2023");

                    b.Property<string>("PaymentOfYearApril2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearApril2023BankRes");

                    b.Property<string>("PaymentOfYearAug2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearAug2023");

                    b.Property<string>("PaymentOfYearAug2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearAug2023BankRes");

                    b.Property<string>("PaymentOfYearDec2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearDec2023");

                    b.Property<string>("PaymentOfYearDec2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearDec2023BankRes");

                    b.Property<string>("PaymentOfYearFeb2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearFeb2023");

                    b.Property<string>("PaymentOfYearFeb2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearFeb2023BankRes");

                    b.Property<string>("PaymentOfYearFeb2024")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearFeb2024");

                    b.Property<string>("PaymentOfYearFeb2024BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearFeb2024BankRes");

                    b.Property<string>("PaymentOfYearJan2024")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearJan2024");

                    b.Property<string>("PaymentOfYearJan2024BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearJan2024BankRes");

                    b.Property<string>("PaymentOfYearJuly2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearJuly2023");

                    b.Property<string>("PaymentOfYearJuly2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearJuly2023BankRes");

                    b.Property<string>("PaymentOfYearJune2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearJune2023");

                    b.Property<string>("PaymentOfYearJune2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearJune2023BankRes");

                    b.Property<string>("PaymentOfYearMarch2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearMarch2023");

                    b.Property<string>("PaymentOfYearMarch2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearMarch2023BankRes");

                    b.Property<string>("PaymentOfYearMay2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearMay2023");

                    b.Property<string>("PaymentOfYearMay2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearMay2023BankRes");

                    b.Property<string>("PaymentOfYearNov2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearNov2023");

                    b.Property<string>("PaymentOfYearNov2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearNov2023BankRes");

                    b.Property<string>("PaymentOfYearOct2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearOct2023");

                    b.Property<string>("PaymentOfYearOct2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearOct2023BankRes");

                    b.Property<string>("PaymentOfYearSep2023")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearSep2023");

                    b.Property<string>("PaymentOfYearSep2023BankRes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("paymentOfYearSep2023BankRes");

                    b.Property<string>("PensionType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pensionType");

                    b.Property<string>("PensionTypeShort")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("pensionTypeShort");

                    b.Property<string>("PresentAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("presentAddress");

                    b.Property<string>("PresentDistrict")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("presentDistrict");

                    b.Property<string>("PresentGpMuncipality")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("present_GP_Muncipality");

                    b.Property<string>("PresentTehsil")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("presentTehsil");

                    b.Property<string>("PresentVillage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("presentVillage");

                    b.Property<string>("PreviousPension")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("previousPension");

                    b.Property<string>("PreviousPensionAccountNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("previousPensionAccountNo");

                    b.Property<string>("PreviousPensionBank")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("previousPensionBank");

                    b.Property<string>("PreviousPensionBankBranch")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("previousPensionBankBranch");

                    b.Property<string>("PreviousPensionBankIfsccode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("previousPensionBankIFSCcode");

                    b.Property<string>("ReSanctionDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reSanctionDate");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("refNo");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remarks2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("remarks2");

                    b.Property<string>("Remarks3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("remarks3");

                    b.Property<string>("RemarksForCorrectionInNameIfscaccountNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("remarksForCorrectionInNameIFSCaccountNo");

                    b.Property<string>("SanctionedByTask")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sanctionedByTask");

                    b.Property<string>("SchemeClarification")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SCHEME_CLARIFICATION");

                    b.Property<string>("SchemeSanctionedByDirJammu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("schemeSanctionedByDirJammu");

                    b.Property<string>("SchemeSanctionedByDirKashmir")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("schemeSanctionedByDirKashmir");

                    b.Property<string>("SchemeSanctionedByDswo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("schemeSanctionedByDSWO");

                    b.Property<string>("SharedWithDeptForVerification")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sharedWithDeptForVerification");

                    b.Property<double?>("Sno")
                        .HasColumnType("float")
                        .HasColumnName("sno");

                    b.Property<string>("TswoPreviousPensionScheme")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tswoPreviousPensionScheme");

                    b.Property<string>("TswoPreviousPensionYesNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tswoPreviousPensionYesNo");

                    b.Property<int?>("TswotehsilCode")
                        .HasColumnType("int")
                        .HasColumnName("TSWOtehsilCode");

                    b.Property<string>("TypeOfDisabilityAsPerUdid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("typeOfDisabilityAsPerUDID");

                    b.Property<int?>("Uid")
                        .HasColumnType("int")
                        .HasColumnName("uid");

                    b.Property<string>("YearActionOnDate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("yearActionOnDate");

                    b.Property<string>("YearActionOnDateVerified1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("yearActionOnDate_verified1");

                    b.ToTable("jkSWdeliveredMay30", (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.MsDistrict", b =>
                {
                    b.Property<int?>("DistrictLgdCode")
                        .HasColumnType("int")
                        .HasColumnName("districtLgdCode");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("districtName");

                    b.Property<string>("DistrictNameForBank")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("districtNameForBank");

                    b.Property<int?>("DivisionCode")
                        .HasColumnType("int")
                        .HasColumnName("divisionCode");

                    b.ToTable("msDistrict", (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.MsDivisionTop500", b =>
                {
                    b.Property<string>("DivisionCode")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("divisionCode")
                        .IsFixedLength();

                    b.Property<string>("DivisionName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("divisionName");

                    b.Property<int?>("StateCode")
                        .HasColumnType("int")
                        .HasColumnName("stateCode");

                    b.ToTable("msDivision_top500", (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.MsTswotehsilTop500", b =>
                {
                    b.Property<int?>("DistrictLgdcode")
                        .HasColumnType("int")
                        .HasColumnName("districtLGDCode");

                    b.Property<int?>("DivisionCode")
                        .HasColumnType("int")
                        .HasColumnName("divisionCode");

                    b.Property<string>("TswoOfficeName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("tswoOfficeName");

                    b.Property<int?>("TswotehsilCode")
                        .HasColumnType("int")
                        .HasColumnName("TSWOtehsilCode");

                    b.Property<string>("TswotehsilName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TSWOtehsilName");

                    b.ToTable("msTSWOtehsil_top500", (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.NsapDatum", b =>
                {
                    b.Property<string>("BankaccountNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankaccount_no");

                    b.Property<string>("BeneficiaryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("beneficiary_name");

                    b.Property<string>("DistrictCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("district_code");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("district_name");

                    b.Property<string>("DuplicateAccountNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("duplicateAccountNo");

                    b.Property<string>("GramPanchayatWardCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gram_panchayat_ward_code");

                    b.Property<string>("GramPanchayatWardName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gram_panchayat_ward_name");

                    b.Property<string>("IfscCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ifsc_code");

                    b.Property<string>("ParentageName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("parentage_name");

                    b.Property<string>("SanctionOrderNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sanction_order_no");

                    b.Property<string>("SchemeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("scheme_name");

                    b.Property<string>("StateCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("state_code");

                    b.Property<string>("StateName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("state_name");

                    b.Property<string>("SubDistrictMunicipalAreaCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sub_district_municipal_area_code");

                    b.Property<string>("SubDistrictMunicipalAreaName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sub_district_municipal_area_name");

                    b.Property<string>("VillageCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("village_code");

                    b.Property<string>("VillageName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("village_name");

                    b.ToTable("nsapData", (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.SearchCount", b =>
                {
                    b.Property<string>("Count")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("((0))");

                    b.ToTable("SearchCount", (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.UpdateHistory", b =>
                {
                    b.Property<int>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UUID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uuid"));

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uuid");

                    b.ToTable("UpdateHistory", (string)null);
                });

            modelBuilder.Entity("PensionTemporary.Models.Entities.User", b =>
                {
                    b.Property<int>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UUID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uuid"));

                    b.Property<int?>("DivisionCode")
                        .HasColumnType("int")
                        .HasColumnName("divisionCode");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Uuid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
